# Generated by Django 5.2.9 on 2026-01-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='genre',
            field=models.CharField(choices=[('action', 'Ação'), ('adventure', 'Aventura'), ('rpg', 'RPG'), ('puzzle', 'Puzzle'), ('strategy', 'Estratégia'), ('edu', 'Educativo'), ('outros', 'Outros')], default='outros', max_length=50, verbose_name='Gênero/Tipo'),
        ),
    ]
