# Generated by Django 5.2.9 on 2026-01-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('active', 'Ativo'), ('finished', 'Finalizado')], default='pending', max_length=20),
        ),
    ]
