# Generated by Django 5.2.9 on 2026-01-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('diretoria', 'Diretoria'), ('associado', 'Associado'), ('afiliado', 'Afiliado'), ('coletivo', 'Coletivo')], default='afiliado', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
