# Generated by Django 5.2.10 on 2026-01-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('diretoria', 'Diretoria'), ('usuario', 'Usuário')], default='usuario', max_length=20),
        ),
    ]
