# Generated by Django 5.2.9 on 2026-01-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='annual_revenue',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Faturamento anual'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='company_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Porte da empresa'),
        ),
    ]
