# Generated by Django 5.2.9 on 2026-01-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representante',
            name='nick_discord',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
