# Generated by Django 5.2.9 on 2026-01-14 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cep',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='complemento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.representante'),
        ),
        migrations.AlterField(
            model_name='company',
            name='site',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='representante',
            name='cep',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='representante',
            name='complemento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='representante',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='representante',
            name='nome_social',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='representante',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
    ]
