# Generated by Django 5.2.9 on 2026-01-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_cep_alter_company_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
