# Generated by Django 5.2.9 on 2026-01-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_representante_nick_discord'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='link_facebook',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='company',
            name='link_instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='company',
            name='link_linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='company',
            name='link_portfolio',
            field=models.URLField(blank=True, verbose_name='Portfólio ou Parceiros'),
        ),
        migrations.AddField(
            model_name='company',
            name='link_twitter',
            field=models.URLField(blank=True, verbose_name='X (Twitter)'),
        ),
        migrations.AddField(
            model_name='company',
            name='link_vagas',
            field=models.URLField(blank=True, verbose_name='Página de Vagas / Carreiras'),
        ),
        migrations.AlterField(
            model_name='company',
            name='site',
            field=models.URLField(blank=True, verbose_name='Site Oficial'),
        ),
    ]
