# Generated by Django 5.2.9 on 2026-01-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_link_facebook_company_link_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='area_atuacao',
            field=models.CharField(choices=[('dev', 'Desenvolvimento'), ('art', 'Arte/Design'), ('audio', 'Áudio/Música'), ('edu', 'Educação'), ('pub', 'Publisher'), ('outros', 'Outros')], default='dev', max_length=50, verbose_name='Área de Atuação'),
        ),
    ]
