# Generated by Django 5.2.9 on 2026-01-25 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_area_atuacao'),
        ('companies', '0004_representante_user'),
    ]

    operations = [
    ]
